### ISSUE TITLE
Concurrent modification causes an exception

### ISSUE THREAD

**Issue by lukashaertel** [maltaisn/msdf-gdx-gen#2]
Running the generator with extended charset ran into a null pointer exception.

```
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.TreeMap.rotateLeft(TreeMap.java:2221)
        at java.base/java.util.TreeMap.fixAfterInsertion(TreeMap.java:2288)
        at java.base/java.util.TreeMap.put(TreeMap.java:580)
        at com.maltaisn.msdfgdx.gen.BMFont$generateGlyphs$1$1.invokeSuspend(BMFont.kt:95)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:1738)

```

This is most likely caused by concurrent modification, as the operation is run in a concurrent context. Replacing the sorted map with a `ConcurrentSkipListMap<Char,FontGlyph>()` solved the issue, but might need some more verification.

The line in question: 
https://github.com/maltaisn/msdf-gdx-gen/blob/8528f3f6cfd314c729956347d2d2315a40638fe0/gen/src/main/kotlin/com/maltaisn/msdfgdx/gen/BMFont.kt#L60

**Comment by maltaisn** [comment]
Good catch! I fixed it in 0.1.2.
